# Generated by Django 4.0.6 on 2022-07-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
